### PR TITLE
Bower dependencies update. Minor code fixes and improvements

### PR DESCRIPTION
**Pull request by maratfakhreev**

### CODE REVIEW

**Comment by maratfakhreev** [comment]
cc @VladimirMikhailov. Your opinion about the `application.coffee` refactoring?

**Comment by VladimirMikhailov** [comment]
@maratfakhreev hey, You're doing a great stuff =)

But I have some concerns about `App.events` method which one contains some "jquery hack" stuff:
 
```coffeescript
App.events = ->
  $(document).on 'click', '.js-link', App.follow
```
- I'm wondering, doesn't backbone support something similar and if it is not, why we have to do it?
- this approach may have consequences - People may wrongly interpret this method as a right place for all other "jquery hacks":

```coffeescript
App.events = ->
  $(document).on 'click', '.js-link', App.follow
  $('.modal').on(click, doSomething)
  # etc
```

We might want to extract the link stuff into separate file and include it as external "Backbone" plugin with gives us exact functionality:

**(fixes and comments are appreciated)**
```coffeescript
# app/extensions/link_to_history.js.coffee

$(document).on 'click', '.js-link',  (event) ->
  event.preventDefault()
  href = $(event.currentTarget).attr('href')
  Backbone.history.navigate(href, trigger: true)
```

What do you think?

Thanks, Vladimir

**Comment by maratfakhreev** [comment]
Thx @VladimirMikhailov. Yeah, `$(document).on 'click', '.js-link', App.follow` is the hack, but I see no other correct solution b/c it's global override for all link actions in the app. I also had doubts about this, and agree with solution to move some logic to separate module but I'm not sure about then naming. Maybe smth like `app/extensions/override.coffee` or  `app/overrides/link.coffee`, so I'm not sure

**Comment by VladimirMikhailov** [comment]
@maratfakhreev yeah, sounds cool, I'm ok with `app/overrides/link.coffee`, btw, we can ask our community =)

**Comment by VladimirMikhailov** [comment]
:+1:

**Pull request merged**
